In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
!pip install streamlit

In [ ]:
df=pd.read_csv(r"C:\Users\bhugt\Downloads\Heart_Disease_Dataset.csv")
df

In [10]:
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,Yes,14.96,Yes,Yes,No,7,6,Yes,Female,25-29,White,Yes,Yes,Fair,17.1,Yes,Yes,Yes
1,Yes,36.93,Yes,Yes,No,3,10,No,Female,30-34,Hispanic,"No, borderline diabetes",Yes,Poor,2.7,Yes,No,No
2,No,18.70,Yes,No,Yes,26,15,No,Male,70-74,Hispanic,No,No,Poor,15.6,Yes,Yes,Yes
3,Yes,31.43,Yes,Yes,Yes,24,20,No,Female,40-44,American Indian/Alaskan Native,"No, borderline diabetes",No,Fair,1.4,No,No,Yes
4,Yes,75.64,No,No,Yes,2,29,No,Male,35-39,White,No,Yes,Excellent,8.8,Yes,Yes,Yes

In [9]:
df.tail()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
100196,No,48.02,No,No,Yes,13,17,No,Female,45-49,White,"No, borderline diabetes",No,Fair,6.4,Yes,No,No
100197,Yes,82.88,No,No,No,29,23,No,Male,75-79,Other,"No, borderline diabetes",Yes,Very good,18.9,Yes,Yes,No
100198,No,39.46,No,Yes,Yes,23,6,Yes,Male,80 or older,Hispanic,Yes,No,Excellent,18.5,Yes,No,Yes
100199,No,46.25,Yes,Yes,Yes,9,14,No,Male,25-29,American Indian/Alaskan Native,No,No,Very good,22.7,Yes,Yes,No
100200,No,39.26,Yes,No,No,10,5,Yes,Female,25-29,Other,"No, borderline diabetes",Yes,Fair,4.1,No,No,Yes

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100201 entries, 0 to 100200
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      100201 non-null  object
 1   BMI               100201 non-null  float64
 2   Smoking           100201 non-null  object
 3   AlcoholDrinking   100201 non-null  object
 4   Stroke            100201 non-null  object
 5   PhysicalHealth    100201 non-null  int64
 6   MentalHealth      100201 non-null  int64
 7   DiffWalking       100201 non-null  object
 8   Sex               100201 non-null  object
 9   AgeCategory       100201 non-null  object
 10  Race              100201 non-null  object
 11  Diabetic          100201 non-null  object
 12  PhysicalActivity  100201 non-null  object
 13  GenHealth         100201 non-null  object
 14  SleepTime         100201 non-null  float64
 15  Asthma            100201 non-null  object
 16  KidneyDisease     100201 non-null  object
 17  SkinCancer        100201 non-null  object
dtypes: float64(2), int64(2), object(14)
memory usage: 13.8+ MB

In [12]:
df.describe()

                 BMI  PhysicalHealth   MentalHealth      SleepTime
count  100201.000000   100201.000000  100201.000000  100201.000000
mean       53.373302       14.503937      14.498239      12.490389
std        23.878712        8.640423       8.658639       6.632122
min        12.020000        0.000000       0.000000       1.000000
25%        32.760000        7.000000       7.000000       6.700000
50%        53.380000       14.000000      15.000000      12.500000
75%        73.950000       22.000000      22.000000      18.200000
max        94.850000       29.000000      29.000000      24.000000

In [13]:
df.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64